kind: ConfigMap
apiVersion: v1
metadata:
  name: trino-catalog
data:
  hive.properties: |-
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minioAdmin
    hive.s3.aws-secret-key=minio1234
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.non-managed-table-writes-enabled=true
    # hive.allow-drop-table=true
    hive.parquet.use-column-names=true
    hive.recursive-directories=true
    hive.metastore.authentication.type=NONE
    hive.metastore-timeout=180s
    hive.s3.connect-timeout=180s
    hive.s3.socket-timeout=180s
  iceberg.properties: |-
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minioAdmin
    hive.s3.aws-secret-key=minio1234
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.metastore-timeout=180s
    hive.s3.connect-timeout=180s
    hive.s3.socket-timeout=180s
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4